# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in RakeFile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rails-units 1.4.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rails-units"
  s.version = "1.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kevin Olbrich, Ph.D."]
  s.date = "2015-02-13"
  s.description = "Provides classes and methods to perform unit math and conversions"
  s.email = ["spike@scpike.net"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "TODO"
  ]
  s.files = [
    "CHANGELOG.txt",
    "Gemfile",
    "LICENSE.txt",
    "Manifest.txt",
    "README.md",
    "RakeFile",
    "TODO",
    "VERSION",
    "lib/rails-units.rb",
    "lib/rails_units/array.rb",
    "lib/rails_units/cache.rb",
    "lib/rails_units/date.rb",
    "lib/rails_units/fixnum.rb",
    "lib/rails_units/math.rb",
    "lib/rails_units/numeric.rb",
    "lib/rails_units/object.rb",
    "lib/rails_units/string.rb",
    "lib/rails_units/time.rb",
    "lib/rails_units/unit.rb",
    "lib/rails_units/unit_definitions.rb",
    "lib/rails_units/version.rb",
    "lib/ruby_units/string.rb",
    "rails-units-1.3.1.gem",
    "rails-units-1.4.1.gem",
    "rails-units-1.6.0.gem",
    "rails-units.gemspec",
    "spec/rails-units/array_spec.rb",
    "spec/rails-units/complex_spec.rb",
    "spec/rails-units/date_spec.rb",
    "spec/rails-units/math_spec.rb",
    "spec/rails-units/numeric_spec.rb",
    "spec/rails-units/object_spec.rb",
    "spec/rails-units/string_spec.rb",
    "spec/rails-units/time_spec.rb",
    "spec/rails-units/unit_spec.rb",
    "spec/spec_helper.rb",
    "test/test_cache.rb",
    "test/test_rails-units.rb"
  ]
  s.homepage = "https://github.com/scpike/rails-units"
  s.rubygems_version = "2.4.5"
  s.summary = "A class that performs unit conversions and unit math"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.5"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.5"])
  end
end

